config/routes.rb
Cemrails::Application.routes.draw do
  resources :events

  devise_for :users

  get 'about' => 'pages#about'
  
  root :to => 'pages#home'

 

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true

  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # we ask the app to authenticate first before letting them in on any of the page.
  before_filter :authenticate_user!, except: [:index]
  # GET /events
  # GET /events.json
  def index
    # it will only show current user events. If we want all events, use Event.all
    #if !user_signed_in?
      @events = Event.all
    #else
      #@events = current_user.events.all
    #end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    # we associate this event with current user
    @event = current_user.events.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = current_user.events.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_event.html.erb
<tr>
  <td><%= event.description %></td>
  <td><%= link_to 'Show', event %></td>
  <% if current_user == event.user %>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/events/_form.html.erb
<%= simple_form_for(@event, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr> 
  </thead>
  
  <tbody>
    <%= render @events %>
  </tbody>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">
      <p>
        <h3><%= @event.description %></h3>
      </p>
      <p>
        Owner: <%= @event.user.name %>
      </p>
      <% if current_user == @event.user %>
        <%= link_to 'Edit', edit_event_path(@event) %> |
      <% end %>
      <%= link_to 'Back', events_path %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    Developed by <%= link_to "Experience Garage, Inc.", "http://experiencegarage.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "CEMRails", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
          <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>

      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CEMRails</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="main container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <%= link_to "One Month Rails", "http://onemonthrails.com" %>
  is a project to teach Rails.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <h1>You're logged in!</h1>
<% else %>
  <div class="hero-unit">
    <h1>Welcome to One Month Rails</h1>
    <p>
      You've found the home page for the
      <%= link_to "One Month Rails", "http://onemonthrails.com" %>
      application.
    </p>
    <p>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-large" %>
    </p>
  </div>
<% end %>